# Generated by Django 4.0.6 on 2022-07-11 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrands',
            name='carModels',
        ),
        migrations.AddField(
            model_name='carmodels',
            name='carBrand',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.carbrands'),
        ),
    ]
