# Generated by Django 4.0.6 on 2022-07-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_carbrands_carmodels_carmodels_carbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.carmodels'),
        ),
    ]
