# Generated by Django 4.0.6 on 2022-07-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
    ]
