# Generated by Django 4.0.6 on 2022-07-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_locations_alter_car_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='carBrand',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CarBrands',
        ),
        migrations.DeleteModel(
            name='CarModels',
        ),
        migrations.DeleteModel(
            name='CarTypes',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
