# Generated by Django 4.0.6 on 2022-08-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_car_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-car_id']},
        ),
    ]
