# Generated by Django 4.0.6 on 2022-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_car_options_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
