# Generated by Django 4.0.6 on 2022-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurl',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
