# Generated by Django 4.0.6 on 2022-08-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_imageurl_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-car_id']},
        ),
    ]
